services:
  # 后端服务
  chatbackend:
    build:
      context: ./ChatBackEnd
      dockerfile: Dockerfile
    container_name: chatbackend
    restart: always
    ports:
      - "3001:3001"
    networks:
      - chat-network

  # 前端 UI
  chatui:
    build:
      context: ./ChatUI
      dockerfile: Dockerfile
    container_name: chat-ui
    restart: always
    ports:
      - "3000:80"
    networks:
      - chat-network

networks:
  chat-network:
    name: ai-chat-network
    external: true
